# Generated by Django 4.2.3 on 2023-07-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSM', '0002_product_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-ptag']},
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
