# Generated by Django 4.2.3 on 2023-08-19 17:17

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PSM', '0003_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chat',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
