# Generated by Django 4.2.3 on 2023-07-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSM', '0003_alter_product_options_product_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('total', models.IntegerField()),
            ],
            options={
                'ordering': ['-total'],
            },
        ),
    ]
