# Generated by Django 4.2.3 on 2023-07-20 10:46

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PSM', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
